name: SlartPing
main: eu.slart.ping.Main
version: 1.0.1
author: xSlart01x
description: Shows the ping of the sender or another player.
commands:
   ping:
      description: Shows the ping of the sender or another player.
      usage: /<command> or /<command> [PlayerName]
   pingreload:
      description: Reloads the configuration.
      usage: /<command>
      aliases: [pingrl]
permissions:
   slartping.*:
      description: Allows to use all SlartPing's commands.
      children:
            slartping.me: true
            slartping.others: true
            slartping.reload: true
      default: op
   slartping.me: 
      description: Allows to use /ping.
      default: true
   slartping.others:
      description: Allows to use /ping [PlayerName].
      default: op
   slartping.reload:
      description: Allows to use /pingreload or /pingrl.
      default: op